config/routes.rb
Todon::Application.routes.draw do
  resources :todos do
    collection do
      post 'sort'
    end
  end
  resources :tags, only: [:index, :destroy, :create, :show]

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/login', to: 'sessions#new', as: 'login'

  root 'index#index'
  get 'index/test'

end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  name       :string(255)
#  deleted    :boolean          default(FALSE)
#  created_at :datetime
#  updated_at :datetime
#

class Tag < ActiveRecord::Base
  has_many :todo

  scope :active, -> { where(deleted: false) }
  scope :user, ->(user) { where('user_id = ?', user.id) }

  validates :name,
    presence: true,
    length: { maximum: 255 }

  def self.create_default_tags(user)
    Tag.create!(name: '仕事', user_id: user.id)
    Tag.create!(name: '趣味', user_id: user.id)
  end

  def self.build(params, user)
    tag = Tag.new(params)
    tag.user_id = user.id
    tag
  end

  def delete
    update_attributes(deleted: true)
    todo.update_all(tag_id: nil)
  end
end

app/models/todo.rb
# == Schema Information
#
# Table name: todos
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  detail     :string(255)      not null
#  tag_id     :string(255)
#  priority   :integer          default(1)
#  end_date   :date
#  deleted    :boolean          default(FALSE)
#  created_at :datetime
#  updated_at :datetime
#

class Todo < ActiveRecord::Base

  belongs_to :tag
  belongs_to :user
  scope :active, -> { where(deleted: false) }
  scope :finished, -> { where(deleted: true) }
  scope :user, ->(user) { where('user_id = ?', user.id) }
  scope :limit_by_tag, ->(tag) { where('tag_id = ?', tag) }

  validates :detail,
    presence: true,
    length: { maximum: 255 }

  def self.build(user, params)
    todo = Todo.new(params)
    todo.user_id = user.id
    todo.priority = Todo.active.user(user).maximum(:priority).to_i + 1
    todo
  end

  def self.sort(user, ids)
    priorities = Todo.active.user(user).where(id: ids).pluck(:priority)
    return false if priorities.count != ids.count

    begin
      Todo.transaction do
        ids.each_with_index do |id, i|
          Todo.update(id, priority: priorities[i])
        end
      end
    rescue => e
      logger.error(e.backtrace)
      return false
    end
    true
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  provider   :string(255)
#  uid        :string(255)
#  name       :string(255)
#  email      :string(255)
#  deleted    :boolean          default(FALSE)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base

  validates :provider,
    length: { maximum: 255 }
  validates :name,
    length: { maximum: 255 }
  validates :email,
    length: { maximum: 255 }

  def self.from_omniauth(auth)
    find_by_provider_and_uid(auth["provider"], auth["uid"]) || create_with_omniauth(auth)
  end

  def self.create_with_omniauth(auth)
    user = create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.email = auth["info"]["email"]
    end
    Tag.create_default_tags(user)
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  before_action :check_logged_in

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def check_logged_in
    check_controller_list = %w(tags todos)
    redirect_to(login_url) if check_controller_list.include?(params[:controller]) && !logged_in?
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    redirect_to todos_url if logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to todos_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

  def failure
    redirect_to root_url, alert: "認証に失敗しました。お手数ですが、もう一度お試し下さい。"
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:destroy]
  def index
    @tags = Tag.active.user(current_user)
    @tag = Tag.new
  end

  def create
    @tag = Tag.build(tag_params(params), current_user)
    @tag.save!
    redirect_to tags_url, notice: 'タグを作成しました！'
  end

  def destroy
    @tag.delete
    redirect_to tags_url, notice: 'タグを削除しました！'
  end

  private
    def set_tag
      @tag = Tag.user(current_user).find(params[:id])
    end

    def tag_params(params)
      params.require(:tag).permit(:name, :deleted)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  def index
    if params[:finished]
      @todos = Todo.finished.user(current_user).order(:priority)
    else
      @todos = Todo.active.user(current_user).order(:priority)
    end
    @tags = Tag.active.user(current_user)
    gon.tags, gon.todos = {}, @todos
    @tags.each{|t| gon.tags[t.id] = t.name}
    @todo = Todo.new
  end

  def show
  end

  def new
    @todo = Todo.new
    @tags = Tag.active.user(current_user)
  end

  def edit
  end

  def sort
    redirect_to todos_url unless params[:ids].present?
    Todo.sort(current_user, params[:ids])
    render nothing: true
  end

  def create
    @todo = Todo.build(current_user, todo_params)
    respond_to do |format|
      if @todo.save
        format.html { redirect_to todos_url, notice: "新しいタスクを登録しました" }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @todo.update_attributes(deleted: true)
    render nothing: true
  end

  private
    def set_todo
      @todo = Todo.find(params[:id])
    end

    def todo_params
      params.require(:todo).permit(:user_id, :detail, :tag_id, :priority, :end_date, :deleted)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_priorty(priority)
    priority_class = nil
    case priority
    when 1
      priority_class = 'danger'
      priority_str = '高'
    when 2
      priority_class = 'warning'
      priority_str = '中'
    when 3
      priority_class = 'info'
      priority_str = '低'
    end
    %Q|<button type="button" class="btn btn-xs btn-#{priority_class}">#{priority_str}</button>|.html_safe if priority_class
  end

  def get_root_url
    if current_user
      todos_url
    else
      root_url
    end
  end

  def todo_line_color(todo)
    if todo.priority == Todo::PRIORITY_HIGH
      'class="danger"'.html_safe
    elsif todo.priority == Todo::PRIORITY_MIDDLE
      'class="warning"'.html_safe
    end
  end

  def date_format(date)
    date.strftime("%1m月%d日")
  end
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/index/index.html.erb
  <div class="row">
    <div class="col-md-12">
      <div id="da-slider" class="da-slider">
        <div class="da-slide da-slide-fromleft da-slide-current">
					<h2>Todon.</h2>
					<a href="<%= login_url %>" class="da-link">ログイン</a>
          <p>しなきゃいけない事、<br>全部ここに</p>
					<div class="da-img"><img src="<%= image_path('parallax/2.png') %>" alt="image01"></div>
				</div>
			</div>
    </div>
  </div>
  <div class="bor"></div>
  <div class="main-box">
    <h4>about</h4>
  <p><span class="color">Todon.</span>はシンプルなTODO管理用Webサービスです。</p>
    <div class="button">
	    <a href="<%= login_url %>" class="da-link">とりあえず使ってみる</a>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Todon</title>
  <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Oswald:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%# include_gon だとphantomjsでエラーが発生する %>
  <%= Gon::Base.render_data({}) %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!-- Favicon -->
  <link rel="shortcut icon" href="/assets/favicon.icon">
</head>
<body>
  <header>
    <div class="container">
      <div class="row">
        <div class="col-md-4 col-sm-4">
          <!-- Logo and site link -->
          <div class="logo">
            <h1><a href="<%= get_root_url %>">Todon<span class="color">.</span></a></h1>
          </div>
        </div>
      </div>
    </div>
  </header>

    <% if logged_in? %>
    <div class="navbar bs-docs-nav" role="banner">
      <div class="container">
        <div class="navbar-header">
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
          <!-- Navigation links starts here -->
          <ul class="nav navbar-nav">
            <!-- Main menu -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">設定<b class="caret"></b></a>
              <!-- Submenus -->
              <ul class="dropdown-menu">
                <li><a href="<%= tags_url %>">タグ設定</a></li>
              </ul>
            </li>
            <li><a href=<%= logout_url %>>ログアウト</a></li>
          </ul>
        </nav>
      </div>
    </div>
    <% else %>
    <br>
    <% end %>

  <div class="content">
    <div class="container">
      <% if flash[:error] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">x</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">x</button>
          <%= flash[:notice] %>
        </div>
      <% end %>
      <div class="row">
        <div class="col-md-12">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
<footer>
	  <div class="row">
      <div class="col-md-12"><p class="copy">
        Copyright © Todon
      </p></div>
    </div>
  </div>
</footer>
</body>
</html>

app/views/tags/index.html.erb
<h3 class="text-info">タグ一覧</h3>
<% @tags.each_with_index do |tag, i| %>
    <a href="<%= tag_url(tag) %>" data-method="delete" data-confirm="指定されたタグを削除します。宜しいですか?"><button type="button" class="badge"><%= tag.name %>&nbsp;&nbsp;&times;</button></a>&nbsp;&nbsp;&nbsp;
<% end %>
<br>
<div class="bor"></div>
<h3 class="text-info">新規タグ作成</h3>
<%= form_for(@tag, :html => {class: 'form-inline'}) do |f| %>
  <%= f.text_field :name, class: 'form-control', placeholder: 'タグ名', style: 'width: 300px' %>
  <%= f.submit(class: 'btn btn-default', value: '作成する') %>
<% end %>

app/views/todos/_form.html.erb
<div class="logreg">
  <div class="row">
    <div class="col-md-12">
      <div class="logreg-page">
      <h3>編集</h3>
      <hr>
      <div class="form">
      <%= form_for(@todo, html: {class: 'form-horizontal'}) do |f| %>
        <% if @todo.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@todo.errors.count, "error") %> 入力エラーがあります:</h2>
            <ul>
            <% @todo.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :detail, class: "control-label col-md-3" %>
          <div class="col-md-9">
            <%= f.text_field :detail %>
          </div>
        </div>

        <% if @tags.present? %>
          <div class="form-group">
            <%= f.label :tag_id, class: "control-label col-md-3" %>
            <div class="col-md-9">
              <%= f.select(:tag_id, @tags.map{|t| [t.name,  t.id] }, prompt: '--') %>
            </div>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :priority, class: "control-label col-md-3" %>
          <div class="col-md-9">
            <%= f.select(:priority, Todo::PRIORITIES.invert, prompt: '--') %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :end_date, class: "control-label col-md-3" %>
          <div class="col-md-9">
            <%= f.date_select :end_date %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-8 col-md-offset-3">
            <%= f.submit(class: 'btn btn-default') %>
          </div>
        </div>
    <% end %>
</div></div></div></div>

app/views/todos/_todos.html.erb
          <div class="logreg" style="background: white"><div class="raw">
            <table class="table table-hover">
              <tbody>
              <tr v-repeat="todos | filterByTag <%= tag_name %>" class="item-{{$index}}">
                  <td class="sortableHandle">
                    <span class="badge">{{tag}}</span>&nbsp;&nbsp;
                    <span class="todo_detail">{{detail}}</span>
                  </td>
                    <td>
                      <a v-if="id" v-on='click: removeTodo(this)' data-method="delete" data-remote="true" href="{{delete_url}}" class="todo-delete-{{$index}}"><span class="icon-trash icon-2x" /></a>
                  </td>
                </tr>
              </tbody>
            </table>
          </div></div>

app/views/todos/create.js.erb
var l = self.app.$data.todos.length - 1;
var last_todo = self.app.$data.todos[l];
if (last_todo) {
  last_todo.id = <%= @todo.id %>;
}

app/views/todos/edit.html.erb
<%= render 'form' %>

app/views/todos/index.html.erb
<div class="row" id="todoapp"><div class="col-md-12">
  <div class="hero">
    <h3><span>Todo一覧</span></h3>
  </div>
  表示内容を変更する：
  <% if params[:finished] %>
    <strong><%= link_to '終ってないタスク', todos_url %></strong>&nbsp;&nbsp;
  <% else %>
    <strong><%= link_to '終ったタスク', todos_url(finished: true) %></strong>&nbsp;&nbsp;
  <% end %>
  <br><br>

  <div class="contact">
    <div class="cwell">
      <%= form_for(@todo, :html => {'v-on' => 'submit: addTodo', class: 'form-inline'}, remote: true) do |f| %>
      <div class="input-group">
        <%= f.select(:tag_id, @tags.map{|t| [t.name,  t.id] }, {prompt: "タグ選択"}, {class: 'form-control_select', 'v-model' => 'newTag'}) %>
      </div>
      <div class="input-group">
        <%= f.text_field :detail, class: 'form-control', placeholder: 'しなきゃいけないこと', 'v-model' => 'newDetail' %>

        <span class="input-group-btn">
          <%= f.submit('作成!', class: 'btn btn-default') %>
        </span>
      </div>
    <% end %>
    </div>
  </div>
  <br>
  <div class="career">
    <div class="tabbable tabs-left">
       <!-- Tabs -->
      <ul class="nav nav-tabs">
        <li class="active"><a href="#tag-all" data-toggle="tab">全て</a></li>
        <% @tags.each do |t| %>
          <li><a href="#tag-<%= t.id %>" data-toggle="tab"><%= t.name %></a></li>
        <% end %>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="tag-all">
          <%= render 'todos', {tag_id: 'all', tag_name: ''} %>
        </div>
        <% @tags.each do |t| %>
        <div class="tab-pane" id="tag-<%= t.id %>">
          <%= render 'todos', {tag_id: t.id, tag_name: t.name} %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div></div>
<br>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @todo.user_id %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @todo.detail %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @todo.tag_id %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @todo.priority %>
</p>

<p>
  <strong>End date:</strong>
  <%= @todo.end_date %>
</p>

<p>
  <strong>Deleted:</strong>
  <%= @todo.deleted %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>